---
- hosts: all
  become: true
  pre_tasks: 
  
  - name: update cache (Ubuntu)
    tags: always  
    apt:
      update_cache:  yes
    changed_when: false 
    when: ansible_distribution == "ubuntu"

- hosts: all
  become: true
  tasks: 
    - name: add ssh key for bob
      tags: always
      authorized_key:
        user: bob
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOE4ZMzqT3gJoxrxtOpCTXV0sfVZzORspLLb14OUViDi Ansible"

- hosts: workstations
  become: true
  tasks:
  
  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

- hosts: web_servers
  become: true
  tasks:
  
  - name: install apache2 and mod-php package, update cache
    tags: apache2, libapach2, ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
     
    when: ansible_distribution == 'ubuntu'

  - name: start httpd (ubuntu)
    tags: apache, libapache2, ubuntu
    service:
      name: apache2
      state: started
      enabled: yes
    when: ansible_distribution == 'ubuntu'

  - name: change email for admin
    tags: apache2, libapache2, ubuntu
    lineinfile:
      path: /etc/apache2/apache2.conf
      regexp: '^ServerAdmin'
      line: serverAdmin somebody@somewhere.net
    register: apache2

  - name: restart apache2 
    tags: apache2, libapache2, ubuntu
    service:
      name: apache2
      state: restarted
    when: apache2.changed

  - name: copy default html to server
    tags: apache2, libapache2, ubuntu
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
