---
- hosts: all
  become: true
  pre_tasks: 
  
  - name: install updates (Ubuntu)
    tags: always  
    apt:
      update_only: yes
      update_cache:  yes
    when: ansible_distribution == "ubuntu"

- hosts: web_servers
  become: true
  tasks:
  
  - name: install apache2 and mod-php package, update cache
    tags: apache2, libapach2, ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
     
    when: ansible_distribution == 'ubuntu'

