---
- hosts: all
  become: true
  pre_tasks: 
  
  - name: install updates (Ubuntu)
    tags: always  
    apt:
      update_only: yes
      update_cache:  yes
    when: ansible_distribution == "ubuntu"

- hosts: web_servers
  become: true
  tasks:
  
  - name: install apache2 and mod-php package, update cache
    tags: apache2, libapach2, ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
     
    when: ansible_distribution == 'ubuntu'
 
  - name: copy default html to server
    tags: apache2, libapache2, ubuntu
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
