- name: install apache2 and mod-php package, update cache
  tags: apache2, libapach2, ubuntu
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest

- name: start httpd (ubuntu)
  tags: apache, libapache2, ubuntu
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes
    

- name: change email for admin
  tags: apache2, libapache2, ubuntu
  lineinfile:
    path: /etc/apache2/apache2.conf
    regexp: '^ServerAdmin'
    line: serverAdmin somebody@somewhere.com
  notify: restart_apache


- name: copy default html to server
  tags: apache2, libapache2, ubuntu
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root


