- name: install apache2 and mod-php package, update cache
  tags: apache2, libapach2, ubuntu
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest

    when: ansible_distribution == 'ubuntu'

- name: start httpd (ubuntu)
  tags: apache, libapache2, ubuntu
  service:
    name: apache2
    state: started
    enabled: yes
    when: ansible_distribution == 'ubuntu'

- name: change email for admin
  tags: apache2, libapache2, ubuntu
  lineinfile:
    path: /etc/apache2/apache2.conf
    regexp: '^ServerAdmin'
    line: serverAdmin somebody@somewhere.net
    register: apache2

- name: restart apache2
  tags: apache2, libapache2, ubuntu
  service:
    name: apache2
    state: restarted
    when: apache2.changed

- name: copy default html to server
  tags: apache2, libapache2, ubuntu
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root

